question_data = [
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "The HTML5 standard was published in 2014.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
     "question": "What does the Prt Sc button do?",
     "correct_answer": "Captures what&#039;s on the screen and copies it to your clipboard",
     "incorrect_answers": ["Nothing",
                           "Saves a .png file of what&#039;s on the screen in your screenshots folder in photos",
                           "Closes all windows"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "On which day did the World Wide Web go online?", "correct_answer": "December 20, 1990",
     "incorrect_answers": ["December 17, 1996", "November 12, 1990", "November 24, 1995"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "In HTML, which non-standard tag used to be be used to make elements scroll across the viewport?",
     "correct_answer": "&lt;marquee&gt;&lt;\/marquee&gt;",
     "incorrect_answers": ["&lt;scroll&gt;&lt;\/scroll&gt;", "&lt;move&gt;&lt;\/move&gt;",
                           "&lt;slide&gt;&lt;\/slide&gt;"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
     "question": "Which of these was the name of a bug found in April 2014 in the publicly available OpenSSL cryptography library?",
     "correct_answer": "Heartbleed", "incorrect_answers": ["Shellshock", "Corrupted Blood", "Shellscript"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "When did the online streaming service &quot;Mixer&quot; launch?", "correct_answer": "2016",
     "incorrect_answers": ["2013", "2009", "2011"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
     "question": "Who invented the &quot;Spanning Tree Protocol&quot;?", "correct_answer": "Radia Perlman",
     "incorrect_answers": ["Paul Vixie", "Vint Cerf", "Michael Roberts"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
     "question": "According to DeMorgan&#039;s Theorem, the Boolean expression (AB)&#039; is equivalent to:",
     "correct_answer": "A&#039; + B&#039;",
     "incorrect_answers": ["A&#039;B + B&#039;A", "A&#039;B&#039;", "AB&#039; + AB"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "What is the number of keys on a standard Windows Keyboard?", "correct_answer": "104",
     "incorrect_answers": ["64", "94", "76"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
     "question": "Who is the founder of Palantir?", "correct_answer": "Peter Thiel",
     "incorrect_answers": ["Mark Zuckerberg", "Marc Benioff", "Jack Dorsey"]}]
